function [scenario, egoVehicle, camera1, radar_RR, radar_RL, radar_R] = env_sim()
%generateSensorData - Returns sensor detections
%    allData = generateSensorData returns sensor detections in a structure
%    with time for an internally defined scenario and sensor suite.
%
%    [allData, scenario, sensors] = generateSensorData optionally returns
%    the drivingScenario and detection generator objects.
% Generated by MATLAB(R) 25.2 (R2025b) and Automated Driving Toolbox 25.2 (R2025b).
% Generated on: 25-Apr-2026 11:17:56

% Create the drivingScenario object and ego car
[scenario, egoVehicle] = createDrivingScenario;

% Create all the sensors
[sensors, numSensors] = createSensors(scenario);
camera1 = sensors{1};   % visionDetectionGenerator
radar_RR = sensors{2};  % Rear Right
radar_RL = sensors{3};  % Rear Left
radar_R = sensors{4};   % Right side radar

% Add sensors to scenario
addSensors(scenario, sensors, egoVehicle.ActorID);

allData = struct('Time', {}, 'ActorPoses', {}, 'ObjectDetections', {}, 'LaneDetections', {}, 'PointClouds', {}, 'INSMeasurements', {});
time  = scenario.SimulationTime;
objectDetections = {};
laneDetections   = [];
ptClouds = {};
insMeas = {};
isValidTime = false(1, numSensors);
isValidLaneTime = false(1, numSensors);

% Generate detections for each sensor
for sensorIndex = 1:numSensors
    sensor = sensors{sensorIndex};
    if ~isa(sensor,'insSensor')
        poses = targetPoses(scenario,sensor.SensorIndex);
    end
    
    % Generate the ego vehicle lane boundaries
    if isa(sensor, 'visionDetectionGenerator')
        maxLaneDetectionRange = min(500,sensor.MaxRange);
        lanes = laneBoundaries(egoVehicle, 'XDistance', linspace(-maxLaneDetectionRange, maxLaneDetectionRange, 101));
    end
    
    type = getDetectorOutput(sensor);
    if strcmp(type, 'Objects only')
        if isa(sensor,'ultrasonicDetectionGenerator')
            [objectDets, isValidTime(sensorIndex)] = sensor(poses, time);
            numObjects = length(objectDets);
        else
            [objectDets, numObjects, isValidTime(sensorIndex)] = sensor(poses, time);
        end
        objectDetections = [objectDetections; objectDets(1:numObjects)];
    elseif strcmp(type, 'Lanes only')
        [laneDets, ~, isValidTime(sensorIndex)] = sensor(lanes, time);
        laneDetections   = [laneDetections laneDets];
    elseif strcmp(type, 'Lanes and objects')
        [objectDets, numObjects, isValidTime(sensorIndex), laneDets, ~, isValidLaneTime(sensorIndex)] = sensor(poses, lanes, time);
        objectDetections = [objectDetections; objectDets(1:numObjects)];
        laneDetections   = [laneDetections laneDets];
    elseif strcmp(type, 'Lanes with occlusion')
        [laneDets, ~, isValidLaneTime(sensorIndex)] = sensor(poses, lanes, time);
        laneDetections   = [laneDetections laneDets];
    elseif strcmp(type, 'PointCloud')
        [ptCloud, isValidPointCloudTime(sensorIndex)] = sensor();
        ptClouds = [ptClouds; ptCloud];
    elseif strcmp(type, 'INSMeasurement')
        insMeasCurrent = sensor(actorState, time);
        insMeas = [insMeas; insMeasCurrent];
        isValidINSTime(sensorIndex) = true;
    end
end

% Aggregate all detections into a structure for later use
if any(isValidTime) || any(isValidLaneTime) || any(isValidPointCloudTime) || any(isValidINSTime)
    allData(end + 1) = struct( ...
        'Time',       scenario.SimulationTime, ...
        'ActorPoses', actorPoses(scenario), ...
        'ObjectDetections', {objectDetections}, ...
        'LaneDetections', {laneDetections}, ...
        'PointClouds',   {ptClouds}, ...
        'INSMeasurements',   {insMeas});
end
end

% % Release all the sensor objects so they can be used again.
% for sensorIndex = 1:numSensors
%     release(sensors{sensorIndex});
% end

%%%%%%%%%%%%%%%%%%%%
% Helper functions %
%%%%%%%%%%%%%%%%%%%%

% Units used in createSensors and createDrivingScenario
% Distance/Position - meters
% Speed             - meters/second
% Angles            - degrees
% RCS Pattern       - dBsm

function [sensors, numSensors] = createSensors(scenario)
% createSensors Returns all sensor objects to generate detections
% Assign into each sensor the physical and radar profiles for all actors
profiles = actorProfiles(scenario);
sensors{1} = visionDetectionGenerator('SensorIndex', 1, ...
    'SensorLocation', [3.7 0], ...
    'Height', 1.3, ...
    'Pitch', 1.5, ...
    'MaxRange', 100, ...
    'DetectorOutput', 'Lanes only', ...
    'Intrinsics', cameraIntrinsics([1814.81018227767 1814.81018227767],[320 240],[480 640]), ...
    'ActorProfiles', profiles);
sensors{2} = drivingRadarDataGenerator('SensorIndex', 2, ...
    'MountingLocation', [-1 -0.9 0.5], ...
    'MountingAngles', [-150 0 0], ...
    'RangeLimits', [0 100], ...
    'HasNoise', false, ...
    'TargetReportFormat', 'Detections', ...
    'HasFalseAlarms', false, ...
    'FieldOfView', [70 5], ...
    'Profiles', profiles);
sensors{3} = drivingRadarDataGenerator('SensorIndex', 3, ...
    'MountingLocation', [-1 0.9 0.5], ...
    'MountingAngles', [150 0 0], ...
    'RangeLimits', [0 100], ...
    'HasNoise', false, ...
    'TargetReportFormat', 'Detections', ...
    'HasFalseAlarms', false, ...
    'FieldOfView', [70 5], ...
    'Profiles', profiles);
sensors{4} = drivingRadarDataGenerator('SensorIndex', 4, ...
    'MountingLocation', [1.8 -0.9 0.5], ...
    'MountingAngles', [-90 0 0], ...
    'RangeLimits', [0 10], ...
    'HasNoise', false, ...
    'DetectionProbability', 1, ...
    'TargetReportFormat', 'Detections', ...
    'HasFalseAlarms', false, ...
    'FieldOfView', [120 5], ...
    'Profiles', profiles);
numSensors = 4;
end

function [scenario, egoVehicle] = createDrivingScenario
% createDrivingScenario Returns the drivingScenario defined in the Designer
% Construct a drivingScenario object.
scenario = drivingScenario;

% Add all road segments
roadCenters = [0 0 0;
    600 0 0];
marking = [laneMarking('Solid', 'Color', [0.98 0.86 0.36])
    laneMarking('Dashed')
    laneMarking('Dashed')
    laneMarking('Solid')
    laneMarking('Solid')];
lanetypes = [laneType('Driving')
    laneType('Driving')
    laneType('Driving')
    laneType('Shoulder')];
laneSpecification = lanespec(4, 'Width', [3.5 3.5 3.5 3], 'Marking', marking, 'Type', lanetypes);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road');

% Add the ego vehicle
egoVehicle = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [0 1.5 0], ...
    'Mesh', driving.scenario.carMesh, ...
    'PlotColor', [38 140 221] / 255, ...
    'Name', 'EgoVehicle');

% --- DODANY POJAZD (TARGET VEHICLE) ---
% Tworzymy nowy obiekt pojazdu na prawym pasie (Y = -2.0).
% Zaczyna 60 metrów za EgoVehicle, aby przy różnicy prędkości 10 m/s 
% zrównać się z nim dokładnie po 6 sekundach.
% targetVehicle = vehicle(scenario, ...
%     'ClassID', 1, ...
%     'Position', [-60 -2.0 0], ...
%     'Mesh', driving.scenario.carMesh, ...
%     'PlotColor', [221 38 38] / 255, ... % Czerwony kolor dla odróżnienia
%     'Name', 'TargetVehicle');

% Definiujemy trajektorię dla TargetVehicle.
% Komenda 'trajectory' przypisuje pojazdowi trasę (od X=-60 do X=400) 
% i wymusza stałą prędkość 25 m/s.
% trajectory(targetVehicle, [-60 -2.0 0; 400 -2.0 0], 25);
end

function output = getDetectorOutput(sensor)
if isa(sensor, 'visionDetectionGenerator')
    output = sensor.DetectorOutput;
elseif isa(sensor, 'lidarPointCloudGenerator')
    output = 'PointCloud';
elseif isa(sensor, 'insSensor')
    output = 'INSMeasurement';
else
    output = 'Objects only';
end
end